#!/usr/bin/python3

## Import modules for CGI handling
import cgi, cgitb
cgitb.enable()
# Create instance of FieldStorage
form = cgi.FieldStorage()
## Get data from fields
name = form.getvalue('name')
email  = form.getvalue('email')


print("Content-type:text/html\r\n\r\n")
print("<HTML>")
print("<HEAD>")
print("<TITLE>Registration Form Confirmation</TITLE>")
print("</HEAD>")
print("<BODY>")
print("    Registration Form")
print("\n")
print('<table align=center border=2>')
print("<tr>")
print("<td> Name:</td>")
print('<td>%s</td>'%(name))
print("</tr>")
print("<tr>")
print('<td>E-mail:</td>')
print('<td>%s</td>'%(email) )
print('</tr>')
print("<tr>")
print('<td>E-mail:</td>')
print('<td>%s</td>'%(email) )
print('</tr>')
print('</table>')
print("\n")
print("\n")
print("Is this information correct ?")
print("  <form method=GET action=/cgi-bin/confirm.py>")
print()
print("  <input type=radio name='confirm' value='yes'> YES   ")
print("  <input type=radio name='confirm' value='no' checked> NO ")
print()
print("  <input type=submit value=Submit>     ")
print("  <input type=reset value=Reset>")
print()
print()
print("  </form>")
print("</BODY>")
print("</HTML>")
